<?php

$fp = dirname( __FILE__ );
fcCodeModule::BasePath($fp.'/');

$om = new fcCodeModule(__FILE__, 'vbz-page.php');
  $om->AddClass('vcTag_html');
  $om->AddClass('vcPage');
  $om->AddClass('vcPageHeader');
  $om->AddClass('vcPageContent');
$om = new fcCodeModule(__FILE__, 'admin.php');
  $om->AddClass('vcAppAdmin');
  $om->AddClass('vcMenuKiosk_admin');
  $om->AddClass('vcPageAdmin');
$om = new fcCodeModule(__FILE__, 'ajax.php');
  $om->AddClass('vcPageAJAX');
  $om->AddClass('vcPage_AJAX_ProcessStatus');
$om = new fcCodeModule(__FILE__, 'cart.php');
  $om->AddClass('vcAppShop_cart');
  $om->AddClass('vcPage_Cart');
  //$om->AddClass('clsSessions_StoreUI');
$om = new fcCodeModule(__FILE__, 'cat.php');
  $om->AddClass('vcAppShop_catalog');
  $om->AddClass('vcMenuKiosk_catalog');
  $om->AddClass('vcCatalogPage');
$om = new fcCodeModule(__FILE__, 'ckout.php');
  $om->AddClass('vcAppShop_checkout');
  $om->AddClass('vcPageCkout');
$om = new fcCodeModule(__FILE__, 'home.php');
  $om->AddClass('vcAppShop_home');
  $om->AddClass('vcPageHome');
$om = new fcCodeModule(__FILE__, 'search.php');
  $om->AddClass('vcAppShop_search');
  $om->AddClass('vcPageSearch');
$om = new fcCodeModule(__FILE__, 'shop.php');
  $om->AddClass('vcAppShop');
  $om->AddClass('vcPage_shop');
  $om->AddClass('vcTag_body_shop');
  $om->AddClass('vcPageContent_shop');
$om = new fcCodeModule(__FILE__, 'topic.php');
  $om->AddClass('vcAppShop_topic');
  $om->AddClass('vcPageTopic');
